name: Bug report
description: Report a bug
body:
  - type: input
    id version
    attributes:
      label: svtplay-dl version
      description: |
        What version do you run?
      placeholder: |
        run svtplay-dl -version
    validations:
      required: true

  - type: input
    attributes:
      label: Python version
      description: |
        What version do you run?
      placeholder: |
        run python --version
    validations:
      required: true

  - type: input
    attributes:
      label: FFmpeg version
      description: |
        What version do you run?
      placeholder: |
        run ffmpeg -version
    validations:
      required: true

  - type: input
    attributes:
      label: Operating system
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Verbose log
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
