name: Bug report
description: Report a bug
body:
  - type: input
    attributes:
      label: svtplay-dl version
      placeholder: |
      svtplay-dl version
    validations:
      required: true

  - type: input
    attributes:
      label: Python version
    validations:
      required: true

  - type: input
    attributes:
      label: Operating system
    validations:
      required: true
      
