name: Bug report
description: Report a bug
body:
  - type: input
    attributes:
      label: svtplay-dl version
      description: |
        What version do you run?
      placeholder: |
        run svtplay-dl -version
    validations:
      required: true

  - type: input
    attributes:
      label: Python version
      description: |
        What version do you run?
      placeholder: |
        run python --version
    validations:
      required: true

  - type: input
    attributes:
      label: FFmpeg version
      description: |
        What version do you run?
      placeholder: |
        run ffmpeg -version
    validations:
      required: true

  - type: input
    attributes:
      label: Operating system
    validations:
      required: true
      
